name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (Required for ZAP)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://example.com'
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP report (JSON format)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: ./zap-report.json

      - name: Upload ZAP report (Markdown format)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: ./zap-report.md

      - name: Upload ZAP report (HTML format)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: ./zap-report.html
