name: OWASP ZAP Scan 

on: push: 
    branches: - main pull_request: branches: - main 

jobs: zap_scan: runs-on: ubuntu-latest steps: - name: Checkout Code uses: actions/checkout@v4 

 - name: Start ZAP Baseline Scan 
    uses: zaproxy/action-baseline@v0.10.0 
    with: 
      target: 'https://your-app-url.com' 
      docker_name: 'owasp/zap2docker-stable' 
      fail_action: false 
      rules_file_name: '.zap/rules.tsv'  # Optional: Custom rules file 
 
  - name: Upload ZAP Report 
    uses: actions/upload-artifact@v4
    with: 
      name: ZAP-Report 
      path: report_html.html 
